#!/bin/bash
#
# script to install MUSIC software with an array. Taken from jamf professional services script
# which can be found here: https://github.com/jamfprofessionalservices/DEP-Notify/blob/master/depNotify.sh

JAMFBIN=/usr/local/bin/jamf
DNLOG=/var/tmp/depnotify.log

# The policy array must be formatted "Progress Bar text,customTrigger". These will be
# run in order as they appear below.
POLICY_ARRAY=(
  "Installing KeyClient,install-keyclient-desktop"
  "Installing Pharos,install-pharos"
  "Installing Symantec,install-SEP-academic"
  "Installing Xerox Drivers,install-xerox-drivers"
  "Installing GarageBand,install-garageband"
  "Installing iMovie,install-imovie"
  "Installing Final Cut Pro X,install-finalcutapps"
  "Installing VLC,install-vlc"
  "Installing Chrome,install-chrome"
  "Installing Flash,install-flash"
  "Installing Max,install-max"
  "Installing PUBLIC Utilities,install-public-utils"
  "Binding to Active Directory,install-bind-to-ad"
)

# Loop to run policies
for POLICY in "${POLICY_ARRAY[@]}"; do
  echo "Status: $(echo "$POLICY" | cut -d ',' -f1)" >> "$DNLOG"
    "$JAMFBIN" policy -event "$(echo "$POLICY" | cut -d ',' -f2)"
done

# don't update inventory, the provisioning script will do that for you!
